apiVersion: v1
kind: Secret
metadata:
    name: fitnessai-secrets
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:4CBgSKKhbfJ8LKiquMENfNM1fhnsiAaH74OYKoIP0k74r7O1oa5V1zIyjxo1v+CQGpWzKgqF18/+0+E53xFRi74ERlP3vVOmA2lZXgc5m7Y3bhSUstmIDyesrWu2jmfsS2tMWyBzcC2o/w==,iv:W7mMgI/92KOKBgHR92dHDEVTkalLb16847RpUrRS6Q0=,tag:Zm2vQDoqRzM6xS10+JA0yQ==,type:str]
    OWNER_EMAIL: ENC[AES256_GCM,data:98Tv+ZN/LLxYh4H1z+y8zz5aXoOvwKQ=,iv:8sPUHZT52wSdtnTYewkRUQuYnY5FCDV1Zp21+E5twMk=,tag:Zb4Rrx2dztf+cLoYMQnzHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdU9hMld1MjVrN1FRUkxO
            RHFCV2lPOEJEek1sb2NVVFk0T2xZVHRqdjJjCmZaYmZGY3I5dFc2UHJDUlRmV3JL
            S1NZdHVBRGlJTGkxZTBRQWRkVno5bmMKLS0tIEF3aks0VVhyUTRLZjFGQ0JwUjJV
            SGRpLzdoSHhFSUM1VkQ2K01PN0NkRU0K4v4J0Ewm1LhxnXbH6luLwKY2p7ipF95d
            VAhKsH/8NedxosnfH/EGGjvDm69XJTEHRGzoNfFNMwQqxBxSv9/Iug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r8ph8yhw6ulpntwa34jn9k9xj6jdkw96afrtuh5wr3pt8cj0d4vq4e286m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T10:07:19Z"
    mac: ENC[AES256_GCM,data:fbGK8Xzgfhske2PPdpYnyeoAj/BNUPuKCjW6DX+sWI6WL+dOXd7OyGLOP1L2Fr9k2lht02ZFk06lgHVnYZ8lMOibM5QQC/4JY13b4fJ78HjWDvZLBEu+n6nPjwNl4ULikjQMF0f3NsnGl55KQJvJeAgYQ20ZWQCrA55q03TL0og=,iv:OeTC33MRpyPgLI9eNgNwIdWy+lINw0vkIaf0WQTNIA0=,tag:R2X4N+qytFEfGWMeCJKepQ==,type:str]
    version: 3.13.3
